query ProfileQuery($id: String!) {
  profile: user(id: $id) {
    _id
    name
    email
    picture
    room {
      _id
      name
      description
      email
      owner {
        _id
      }
      stuffs {
        _id
        name
        description
        category
        picture
      }
    }
  }
}