query ProfileQuery($id: String!) {
  profile: user(id: $id) {
    _id
    name
    email
    room {
      _id
      name
      description
      email
      stuffs {
        _id
        name
        description
        category
        picture
      }
    }
  }
}

mutation SaveStuff($stuff: StuffInput!) {
  addStuff(stuff: $stuff) {
    _id
    name
    category
    description
    picture
    price
  }
} 