query ProfileQuery($id: String!) {
  profile: user(id: $id) {
    _id
    name
    email
    room {
      _id
      name
      description
      email
      stuffs {
        _id
        name
        description
        category
        picture
      }
    }
  }
}

mutation CreateRoom($room: RoomInput!) {
    addRoom(room: $room) {
        _id
    }
}

mutation DeleteRoom($id: String!) {
    deleteRoom(id: $id) {
        _id
    }
}

mutation SaveStuff($stuff: StuffInput!) {
  addStuff(stuff: $stuff) {
    _id
    name
    category
    description
    picture
    price
  }
} 

mutation UpdateStuff($stuff: StuffInput!) {
  updateStuff(stuff: $stuff) {
    _id
    name
    category
    description
    picture
    price
  }
}

mutation DeleteStuff($id: String!) {
    deleteStuff(id: $id) {
        _id
    }
}