query RoomsQuery {
    rooms {
        _id
        name
        description
        picture
    }
}

subscription RoomsSubscription {
    watchRooms {
        _id
        name
        description
        picture
    }
}