mutation AddStuff($stuff: StuffInput) {
    addStuff(stuff: $stuff) {
        name
        description
        price
    }
}

mutation UpdateStuff($stuff: StuffInput) {
    updateStuff(stuff: $stuff) {
        name
        description
        price
    }
}

mutation DeleteStuff($stuff: StuffInput) {
    deleteStuff(stuff: $stuff) {
        name
        description
        price
    }
}