type Room {
    _id: String!
    owner: User!
    name: String!
    description: String
    email: String
    phoneNumber: String
    picture: String
    categories: [String] # A room class its stuff under categories
    stuffs: [Stuff]
    orders: [Order]
}
input RoomInput {
    _id: String!
    userId: String!
    name: String! # Room Name
    description: String # Room Description
    email: String,
    phoneNumber: String,
    picture: String # Room pictures as a list of hash
}