type User {
    _id: String!
    name: String
    email: String!
    picture: String
    password: String! #hash256 password
    room: Room #user rooms listed by Id
}
input UserLogin {
    email: String!
    password: String!
}

input UserInput {
    _id: String
    name: String!
    email: String!
    picture: String
    password: String!
    roomId: String
}
input UserSignup {
    _id: String!
    name: String!
    email: String!
    password: String!
}
