mutation SaveOrder($order: OrderInput!) {
    updateOrder(order: $order) {
        _id
    }
}

mutation DeleteOrder($id: String!) {
    deleteOrder(id: $id) {
        _id
    }
}

mutation SaveRoom($room: RoomInput!) {
    updateRoom(room: $room) {
        _id
    }
}

mutation DeleteRoom($id: String!) {
    deleteRoom(id: $id) {
        _id
        name
    }
}

mutation SaveStuff($stuff: StuffInput!) {
    updateStuff(stuff: $stuff) {
        _id
    }
}

mutation DeleteStuff($id: String!) {
    deleteStuff(id: $id) {
        _id
        name
    }
}

mutation SaveUser($user: UserInput!) {
    updateUser(user: $user) {
        _id
    }
}

mutation Signup($user: UserSignup!) {
    signup(user: $user) {
        _id
        name
    }
}

query Login($login: UserLogin!) {
    login(login: $login) {
        _id
        name
    }
}

mutation DeleteUser($id: String!) {
    deleteUser(id: $id) {
        _id
        name
    }
}

