query LoadRoom( $userId: String! ) {
    user( id: $userId ) {
        room {
            _id
            name
        }
    }
}

subscription WatchOrders( $roomId: String! ) {
    orders: watchOrders( id: $roomId ) {
        _id
        created
        payed
        treated
        created
        amount
        stuffs {
            _id
            name
            category
            price
        }
        client {
            _id
            name
        }
    }
}