query LoadRoom( $userId: String! ) {
    user( id: $userId ) {
        room {
            _id
            name
            orders {
                _id
                message
                created
                payed
                treated
                amount
                stuffs {
                    _id
                    name
                    category
                    price
                }
                client {
                    _id
                    name
                }
            }
        }
    }
}

subscription WatchOrders( $roomId: String! ) {
    orders: watchOrders( id: $roomId ) {
        _id
    }
}